name: talatah
description: secure and simple password manager.

publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.1
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
